### PR TITLE
algos

### PR DESCRIPTION
**Pull request by maxcomperatore**
remove_copy_if, algorithm_replace, algorithm_replace_if

### CODE REVIEW

**Comment by KaisenAmin** [comment]
Thank you very much for implementing these functions
Did you test or should I do it?
If you did, add the examples to the README file in the algorithm.

**Comment by maxcomperatore** [comment]
Tested and added examples

**Comment by maxcomperatore** [comment]
btw, do you want me to document the rest of the algos like i did in this pr?

**Comment by KaisenAmin** [comment]
Very good, thank you
Yes, I definitely welcome doxygen for the rest of the functions.

**Pull request merged**
